add OSTH
noraj/OSCP-Exam-Report-Template-Markdown pull request #56
Opened 2024-10-20 17:09 UTC by jason3e7

add Offensive Security Threat Hunting Certification

2024-10-29 20:33 UTC, noraj requested changes
Thanks a lot for your contribution! That's awesome.
I was very busy, sorry for the delay before a proper review.

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +- Escalate Incident to Incident Response Team:
```suggestion
1. **Escalate Incident to Incident Response Team:**
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +- Continued Support and Analysis:
```suggestion
2. **Continued Support and Analysis:**
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +- Continuous Improvement and Training:
```suggestion
3. **Continuous Improvement and Training:**
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +
```suggestion
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +```
```suggestion
```default
```

https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/blob/master/FAQ.md#syntax-highlight-style-ignored-when-no-language-provided

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +...
```suggestion
[…]
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +... | ... | ...
```suggestion
[…] | […] | […]
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +... | ... | ...
```suggestion
[…] | […] | […]
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +...             | ...
```suggestion
[…]             | […]
```

2024-10-29 20:33 UTC, noraj commented on src/OSTH-exam-report-template_OS_v1.md
> +...            | ...
```suggestion
[…]            | […]
```

2024-10-31 01:13 UTC, jason3e7 commented
Hi @noraj, I committed the changes as requested.
But the indentation changed from two spaces to four spaces.
Then ordered list and unordered sublist will be displayed correctly in the generated pdf.
OSTH-exam-report-template_OS_v1.md, line 75 ~ 85

2024-10-31 21:37 UTC, merged